# Numpy
### Если задания покажутся сложными, рекомендую пройти краткий курс по основам numpy [ссылка1](https://stepik.org/lesson/241329/step/1?unit=213910), [ссылка2](https://stepik.org/lesson/16462/step/1?unit=4283)

In [ ]:
import numpy as np
import random
import scipy.stats as sps
import cv2
import time


### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [ ]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела? Ответ: вывела размер матрицы в формате кол-во строк и кол-во столбцов.
# ========
print("ранг a =",a.ndim, "\nранг b =", b.ndim)
print("размер матрицы a =",a.shape,"\nразмер матрицы b =",b.shape)
# ========
print(a)
print(b)

ранг a = 2 
ранг b = 2
размер матрицы a = (100, 100) 
размер матрицы b = (100, 100)
[[0.52728519 0.01536284 0.44423115 ... 0.13568458 0.3552492  0.83654502]
 [0.99050586 0.82805473 0.96852725 ... 0.38626123 0.6743334  0.4549979 ]
 [0.895241   0.1798512  0.68131617 ... 0.83007775 0.14213342 0.74744913]
 ...
 [0.23974435 0.88330036 0.90733241 ... 0.10629252 0.89565902 0.04224264]
 [0.344766   0.37844446 0.04383528 ... 0.72720854 0.82946284 0.3279414 ]
 [0.0248322  0.59163254 0.63565452 ... 0.41084197 0.64297676 0.15149658]]
[[0.00662287 0.70177295 0.50852985 ... 0.25056296 0.52713234 0.71054263]
 [0.31589234 0.85822946 0.48511513 ... 0.42719007 0.99975359 0.56238324]
 [0.19873148 0.79001179 0.81841606 ... 0.54300864 0.45526717 0.24175165]
 ...
 [0.74037394 0.86391545 0.57068261 ... 0.55417871 0.78987729 0.24780735]
 [0.50471537 0.87205012 0.53986448 ... 0.01904173 0.94279199 0.68638082]
 [0.47481268 0.33799624 0.31474142 ... 0.09617276 0.09757824 0.60027953]]


Без использования numpy

In [ ]:
def mult(a, b):
    result = [[0] * len(b[0]) for _ in range(len(a))]
    for i in range(len(a)):
        for j in range(len(b[0])):
            for k in range(len(b)):
                result[i][j] += a[i][k] * b[k][j]
    return result


C использованием numpy

In [ ]:
def np_mult(a, b):
    result = np.dot(a, b)
    return result

In [ ]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 715 ms, sys: 0 ns, total: 715 ms
Wall time: 719 ms


In [ ]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 6.04 ms, sys: 0 ns, total: 6.04 ms
Wall time: 10.1 ms


In [ ]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

1.518429826319334e-11

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [ ]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.8130602  0.66307239 0.80954058] [0.65299414 0.23199435 0.4306037 ]


In [ ]:
def scalar_product(a,b):
    s = 0
    for i in range(len(a)):
      s += a[i] * b[i]
    return s

In [ ]:
def np_scalar_product(a,b):
    s = np.dot(a, b)
    return s

In [ ]:
start_time = time.time()
product_1 = scalar_product(a,b)
end_time = time.time()
print("Скаляр без использования NumPy:", product_1)
print("Время без NumPy:", end_time - start_time, "секунд")

start_time = time.time()
product_2 = np_scalar_product(a,b)
end_time = time.time()
print("Скаляр с NumPy:", product_2)
print("Время с NumPy:", end_time - start_time, "секунд")

Скаляр без использования NumPy: 1.0333437579205806
Время без NumPy: 0.00013899803161621094 секунд
Скаляр с NumPy: 1.0333437579205806
Время с NumPy: 0.0001678466796875 секунд


Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

**Ответ:** Потому что они оптимизированы для такой работы. NumPy использует векторизацию, которая минимизирует использование циклов при работе с массивами. Скорость в NumPy высокая за счёт оптимизированных алгоритмов.

------------------

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [ ]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
  res = np.sum(a.diagonal()[::2])
  return res

In [ ]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[5, 4, 6, 7, 9],
       [8, 1, 6, 8, 6],
       [8, 2, 8, 6, 8],
       [1, 1, 5, 7, 6],
       [5, 4, 6, 8, 9]])

In [ ]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 228 µs, sys: 0 ns, total: 228 µs
Wall time: 264 µs


22

### Задание 4
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $x = (x_1, x_2, \ldots, x_n)$ массива $X$  строит строчку $s = (s_1, s_2, \ldots, s_n)$, где $s_k=\frac{x_1+...+x_k}{k}$, а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и $X$.

In [ ]:
def np_sec_av(X):
  cumsum = np.cumsum(X, axis=1)
  result = cumsum / np.arange(1, X.shape[1] + 1)
  return result

In [ ]:
# зададим некоторую последовательность и проверим ее на ваших функциях.
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = np.random.uniform(size=(10**3, 10))
%time S2 = np_sec_av(A)

CPU times: user 254 µs, sys: 40 µs, total: 294 µs
Wall time: 305 µs


### Задание 5
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [ ]:
# функция, решающая задачу с помощью NumPy
def np_encode(a):
  a = np.array(a)
  diff = np.concatenate(([1], np.diff(a)))
  x = a[diff != 0]
  num = np.diff(np.where(diff != 0))
  return x, num

In [ ]:
from itertools import groupby
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
x, num = np_encode(X)
print(x)
print(num)
%time x, num = np_encode(X)

[1 2 3 1 5 2 3]
[[1 2 2 2 2 1]]
CPU times: user 133 µs, sys: 0 ns, total: 133 µs
Wall time: 139 µs


### Задание 6

Пусть задан некоторый одномерный массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. Массив $X$ при этом должен остаться *без изменений*. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке.  

Пример:  
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [ ]:
# функция, решающая задачу с помощью NumPy
from copy import copy

import numpy as np

def np_transformation(X, a=1):
  result = np.copy(X)
  result[1::2] = a
  result[::2] = result[::2]**3
  result = np.concatenate((X, result[::-1]), axis=None)
  result = result[::-1]
  return result

In [ ]:
X = np.array([i for i in range(1, 10, 2)])
%time S2 = np_transformation(X, 5)

CPU times: user 0 ns, sys: 254 µs, total: 254 µs
Wall time: 298 µs
